import { useEffect, useState } from 'react'
import './styles.css'

const base = 'https://chalakgo.onrender.com'
const api = async (path, options = {}) => { const token = sessionStorage.getItem('chalakgo_admin_token'); const response = await fetch(base + path, { credentials: 'include', headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers }, ...options }); const data = await response.json(); if (!response.ok) throw Error(data.message || 'Request failed.'); return data }
const list = value => String(value || '').split('\n').map(item => item.trim()).filter(Boolean)

export default function JaipurTourAdmin() {
  const [tour, setTour] = useState(null), [notice, setNotice] = useState('')
  useEffect(() => { api('/api/services/admin').then(items => { const item = items.find(service => service.slug === 'jaipur-tour'); if (!item) throw Error('Jaipur Tour service not found.'); const plans = item.tourPlans || []; setTour({ ...item, featuresText: (item.features || []).join('\n'), onePrice: plans.find(plan => plan.days === 1)?.price || '', onePlaces: (plans.find(plan => plan.days === 1)?.places || []).join('\n'), twoPrice: plans.find(plan => plan.days === 2)?.price || '', twoPlaces: (plans.find(plan => plan.days === 2)?.places || []).join('\n') }) }).catch(error => setNotice(error.message)) }, [])
  if (!tour) return <main className="admin-loading">Loading Jaipur Tour editor…</main>
  const set = (key, value) => setTour(old => ({ ...old, [key]: value }))
  const save = async event => { event.preventDefault(); try { const body = { name: tour.name, slug: 'jaipur-tour', price: tour.price, eyebrow: tour.eyebrow, detail: tour.detail, image: tour.image, isActive: tour.isActive, features: list(tour.featuresText), tourPlans: [{ days: 1, price: tour.onePrice, places: list(tour.onePlaces) }, { days: 2, price: tour.twoPrice, places: list(tour.twoPlaces) }] }; const saved = await api(`/api/services/${tour._id}`, { method: 'PUT', body: JSON.stringify(body) }); setTour(old => ({ ...old, ...saved })); setNotice('Jaipur Tour details saved successfully.') } catch (error) { setNotice(error.message) } }
  return <main className="admin-loading"><form className="card editor" onSubmit={save} style={{ width: 'min(940px, calc(100vw - 32px))', margin: '32px auto' }}><div className="form-head"><div><small>CHALAKGO ADMIN · SERVICES</small><h2>Jaipur Tour editor</h2><p>Manage all tour information, 1-day/2-day packages, prices and places.</p></div><a className="back" href="/">Back to dashboard</a></div>{notice && <p className="empty">{notice}</p>}<div className="grid"><label className="field"><span>Service name</span><input required value={tour.name || ''} onChange={e => set('name', e.target.value)} /></label><label className="field"><span>Starting price</span><input value={tour.price || ''} onChange={e => set('price', e.target.value)} /></label><label className="field wide"><span>Short heading</span><input value={tour.eyebrow || ''} onChange={e => set('eyebrow', e.target.value)} /></label><label className="field wide"><span>Service description</span><textarea value={tour.detail || ''} onChange={e => set('detail', e.target.value)} /></label><label className="field wide"><span>Tour image URL</span><input value={tour.image || ''} onChange={e => set('image', e.target.value)} /></label><label className="field wide"><span>Service features (one per line)</span><textarea value={tour.featuresText || ''} onChange={e => set('featuresText', e.target.value)} /></label><label className="field"><span>1-day plan price</span><input required value={tour.onePrice} onChange={e => set('onePrice', e.target.value)} /></label><label className="field"><span>2-day plan price</span><input required value={tour.twoPrice} onChange={e => set('twoPrice', e.target.value)} /></label><label className="field"><span>1-day places (one per line)</span><textarea required value={tour.onePlaces} onChange={e => set('onePlaces', e.target.value)} /></label><label className="field"><span>2-day places (one per line)</span><textarea required value={tour.twoPlaces} onChange={e => set('twoPlaces', e.target.value)} /></label></div><label className="toggle"><input type="checkbox" checked={!!tour.isActive} onChange={e => set('isActive', e.target.checked)} /><i></i><span><b>Publish Jaipur Tour</b><small>Show this service on the website and navbar</small></span></label><div className="form-footer"><button className="primary">Save Jaipur Tour details</button></div></form></main>
}
